version: '3.8'

services:
  delivery-api:
    container_name: delivery-api
    build:
      dockerfile: Dockerfile
      context: .
    image: delivery-api
    ports:
      - '8000:8000'
    volumes:
      - '.:/app'
      - '/app/node_modules'
    restart: always
